spring:
  datasource:
    url: jdbc:h2:mem:salesorderdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

distributor:
  url: http://localhost:8081
