spring:
  datasource:
    url: jdbc:postgresql://salesorder_postgres:5432/salesorder
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: false

distributor:
  url: http://distributor-mock:8082
