spring:
  datasource:
    url: jdbc:postgresql://salesorder_postgres:5432/salesorder
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: false

management:
  datadog:
    metrics:
      export:
        enabled: true
        api-key: ${DD_API_KEY}
        step: 30s
        host-tag: host
        uri: https://api.datadoghq.com
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus